### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by victorchall** [Oletus/float16-simulator.js#1]
I used some of your js functions as a basis to write a python script/tkinter ui to toy around with looking a floating point precisions and wanted to released it, but didn't want to do so without your permission.  What is your intent for the license?

![image](https://github.com/Oletus/float16-simulator.js/assets/15839076/a81ebfee-c350-47c2-977f-34b0446f0d11)

**Comment by Oletus** [comment]
Thanks for asking! I added a MIT license to the repo.

**Comment by victorchall** [comment]
Awesome, thanks for sharing the code!

**Comment by victorchall** [comment]
Project up if you're interested https://github.com/victorchall/fp-precision-graph
